[package]
name = "talk-rs"
version = "0.1.0"
authors = ["Erik Aker <eraker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# serde = "0.4"